config/routes.rb
Railsplate::Application.routes.draw do
  root to: 'home#index'

  resources :patients
  namespace :patients do
    get ":id/doctor-signup/:email"  => "invites#new",
                                        as: :new_doctor
    post ":id/doctor-signup/"       => "invites#create",
                                        as: :create_doctor
    post ":id/carer-signup/"        => "invites#create_carer",
                                        as: :create_carer
    get ":id/doctor-signin/:email"  => "invites#existing",
                                        as: :existing_doctor
    post ":id/session"              => "invites#session_and_associate",
                                        as: :doctor_session
    get ":id/doctor-signin/"        => "invites#signin",
                                        as: :signin

    get ":id/doctor/:id"            => "doctors#show",
                                        as: :doctor
    get ":id/doctors"               => "doctors#index",
                                        as: :doctors
    post ":id/doctors"              => "doctors#invite_doctor",
                                        as: :invite_doctor

    get ":id/carers"                => "carers#index",
                                        as: :carers
    get ":id/carers/:id"            => "carers#show",
                                        as: :carer
    post ":id/carers"               => "carers#invite_carer",
                                        as: :invite_carer
    get ":id/carer-signup/:email"   => "carers#new",
                                        as: :new_carer
  end

  resources :doctors do
  end
  namespace :doctors do
    get ":id/patient-signin/:email" => "invites#existing",
                                        as: :existing_patient
    post ":id/session"              => "invites#session_and_associate",
                                        as: :patient_session

    post ":id/patient-signup/"      => "invites#create",
                                        as: :create_patient
    get ":id/patient-signup/:email" => "invites#new",
                                        as: :new_patient
    post ":id/patients"             => "patients#invite_patient",
                                        as: :invite_patient
    get ":id/patient/:id"           => "patients#show",
                                        as: :patient
    get ":id/patients"              => "patients#index",
                                        as: :patients
  end

  resources :carers, only: [:show]
  namespace :carers do
    resources :patients, only: [:show]

  end

  resources :sessions
  get "logout"                      => "sessions#destroy_doctor",
                                        as: :logout_doctor
  get "logout"                      => "sessions#destroy_patient",
                                        as: :logout_patient
  get "logout"                      => "sessions#destroy_carer",
                                        as: :logout_carer

end

app/models/carer.rb
class Carer < ActiveRecord::Base
	attr_accessible :username, :email, :phone, :relationship, :password, :patient_id

	belongs_to :patient

	authenticates_with_sorcery!

	validates :username, :email, :phone, :relationship, presence: true
	validates :email, uniqueness: true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :phone, :password

  has_many :healthcares
  has_many :carers
  has_many :doctors, :through => :healthcares
end

app/controllers/carers/patients_controller.rb
class Carers::PatientsController < ApplicationController
	def show
		@patient = Patient.find(params[:id])
	end
end

app/controllers/carers_controller.rb
class CarersController < ApplicationController
	def show
		@carer = Carer.find(params[:id])
		@patient = Patient.find(@carer.patient_id)
	end
end

app/controllers/doctors/patients_controller.rb
class Doctors::PatientsController < ApplicationController
	def index
		@doctor = Doctor.find(params[:id])
		@doctors_patients = @doctor.patients
	end

	def show
		@patient = Patient.find(params[:id])
	end

	def invite_patient
		doctor = Doctor.find(params[:id])
		patient = {username: params["patient-username"], email: params["patient-email"]}
		DoctorPatientMailer.invite_patient(doctor, patient).deliver
		redirect_to :back, notice: 'Invite sent!'
	end
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
	def new
		@patient = Patient.new
	end

	def create
		patient = Patient.new(params[:patient])
		if patient.save
			redirect_to patient_path(patient), notice: "Successfully signed in"
		else
			redirect_to root_path, notice: "Not signed up! Try again :)"
		end
	end

	def show
		@patient = Patient.find(params[:id])
	end
end

app/controllers/patients/carers_controller.rb
class Patients::CarersController < ApplicationController
	def index
		@patient = Patient.find(params[:id])
	end

	def new
		@carer = Carer.new(username: params[:username], email: params[:email])
		@patient = Patient.find(params[:id])
	end

	def show
		@carer = Carer.find(params[:id])
	end

	def invite_carer
		patient = Patient.find(params[:id])
		carer = {'carer-username' => params["carer-username"], 'carer-relationship'=> params['carer-relationship'], 'carer-email'=> params["carer-email"]}

		PatientCarerMailer.invite_carer(patient, carer).deliver
		redirect_to :back, notice: 'Invite sent!'
	end
end

app/controllers/patients/doctors_controller.rb
class Patients::DoctorsController < ApplicationController
	def index
		@patient = Patient.find(params[:id])
		@patients_doctors = @patient.doctors
	end

	def show
		@patient_doctor = Doctor.find(params[:id])
	end

	def invite_doctor
		patient = Patient.find(params[:id])
		doctor = {username: params["doctor-username"], email: params["doctor-email"]}
		PatientDoctorMailer.invite_doctor(patient, doctor).deliver
		redirect_to :back, notice: 'Invite sent!'
	end

	def create
		binding.pry
	end
end

app/controllers/patients/invites_controller.rb
class Patients::InvitesController < ApplicationController
	def new
		@doctor = Doctor.new(username: params[:username], email: params[:email])
		@patient = Patient.find(params[:id])
	end

	def create
		patient = Patient.find(params[:id])
		doctor = build_doctor(params)
		if doctor.save
			associate_doctor_patient(doctor, patient)
			session[:doctor_id] = doctor.id
			redirect_to doctor_path(doctor), notice: account_success
		else
			redirect_to :back, notice: account_error
		end
	end

	def create_carer
		patient = Patient.find(params[:id])
		carer = build_carer(params, patient.id)
		if carer.save
			patient.carers << carer
			login_carer(carer.id)
			redirect_to carer_path(carer), notice: account_success
		else
			redirect_to :back, notice: account_error
		end
	end

	def login_carer(carer_id)
		session[:carer_id] = carer_id
	end

	def account_error
		"Account not created, please try again!"
	end

	def account_success
		"Account Created!"
	end

	def build_carer(params, patient_id)
		# set the carer to patient association
		Carer.new(
			username: params[:username],
			email: params[:email],
			relationship: params[:relationship],
			phone: params[:phone],
			password: params[:password],
			patient_id: patient_id
			)
	end

	def build_doctor(params)
		Doctor.new(
			username: params[:username],
			email: params[:email],
			phone: params[:phone],
			medical_school: params[:medical_school],
			practice: params[:practice],
			speciality: params[:speciality],
			password: params[:password]
			)
	end

	def associate_doctor_patient(doctor, patient)
		Healthcare.create(doctor_id: doctor.id,patient_id: patient.id)
	end

	def existing
		@patient = Patient.find(params[:id])
	end

	# Associate without new Patient/Doctor record creation
	def session_and_associate
		patient = Patient.find(params[:id])
		doctor = Doctor.where(email: params[:email]).first
		if associate_doctor_patient(doctor, patient)
			session[:doctor_id] = doctor.id
			redirect_to doctors_patient_path(doctor, patient), notice: 'Logged in and association made!'
		else
			redirect_to :back, notice: 'Your details may have been entered incorrectly, please try again'
		end
	end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def new
		@patient = Patient.new
	end

	def create
		patient = Patient.new(params[:patient])
		if patient.save
			auto_login(patient)
			redirect_to patient_path(patient), notice: "Successfully signed in"
		else
			redirect_to root_path, notice: "Not signed up! Try again :)"
		end
	end

	def show
		@patient = Patient.find(params[:id])
		@patients_doctors = @patient.doctors
	end
end

app/views/patients/carers/index.html.erb
<h3>My Carers</h3>
<div id='my-carers'>
<!-- TODO: List the associated carers -->
	<% @patient.carers.each do |carer|%>
		<ul>
			<li><%= link_to carer.username.capitalize, patients_carer_path(@patient, carer) %></li>
		</ul>
	<%end%>
</div>
<h3>Invite a Carer</h3>
<div id="invite-carer">
	<form name="input" action='/patients/<%=@patient.id%>/carers' method="post" >
		<p>
			<label for="carer-username">Carer Name:</label>
			<input type="text" name="carer-username">
		</p>
		<p>
			<label for="carer-relationship">Relationship:</label>
	    <select name='carer-relationship'>
         <option>Family</option>
         <option>Friend</option>
	    </select>
		</p>
		<p>
		<label for="carer-email">Email:</label>
		<input type="text" name="carer-email">
		</p>
		<p>
			<input type="submit" value="Invite">
		</p>
	</form><!-- form#invite-doctor-email -->
</div>

app/views/patients/carers/new.html.erb
<!-- TODO: Jumping the gun to the accepting of the invite, need to backtrack to the original patient invites the carer part -->
<div id='carer-signup'>
  <h2>New Carer Form</h2>
  <p>You have been invited by <%= @patient.username.capitalize %> to be their carer</p>
  <form name="input" action='/patients/<%=@patient.id%>/carer-signup' method="post" >

  <h3>Your Patient's Details</h3>
  <p>
   <label for="patient-name">Patient Name</label>
   <input name="patient-name" type="text" id="login" readonly value='<%= @patient.username %>' style="border:none;">
  </p>
  <p>
   <label for="patient-email">Patient Email</label>
   <input name="patient-email" type="text" id="login" readonly value='<%= @patient.email %>' style="border:none;">
  </p>
  <h3>Your Details</h3>
  <p>
   <label for="username">Username</label>
   <input type="text" name="username" id="username" placeholder="Your Tredule Username">
  </p>
  <p>
   <label for="email">Email</label>
   <input type="text" name="email" id="email" placeholder="example@example.com">
  </p>
    <label for="relationship">Relationship to <%= @patient.username.capitalize %>:</label>
    <select name='relationship'>
       <option>Family</option>
       <option>Friend</option>
    </select>
  <p>
   <label for="phone">Phone</label>
   <input type="text" name="phone" id="phone" placeholder="(XXX)-XXX-XXXX">
  </p>
  <p>
    <label for="password">Password</label>
    <input name="password" type="text" id="password" >
  </p>
  <p>
    <input type="submit" value="Sign-Up!">
  </p>
  </form>
</div>

app/views/patients/carers/show.html.erb
<h1>Your Carer</h1>
<div id='carer-details'>
	<ul>
		<li><%= @carer.username %></li>
		<li><%= @carer.email %></li>
		<li><%= @carer.phone %></li>
		<li><%= @carer.relationship %></li>
	</ul>
</div>