config/routes.rb
Railsplate::Application.routes.draw do
  root to: 'home#index'

  resources :patients
  namespace :patients do
    get ":id/doctor-signup/:email"  => "invites#new",
                                        as: :new_doctor
    post ":id/doctor-signup/"       => "invites#create",
                                        as: :create_doctor
    post ":id/carer-signup/"        => "invites#create_carer",
                                        as: :create_carer
    get ":id/doctor-signin/:email"  => "invites#existing",
                                        as: :existing_doctor
    post ":id/session"              => "invites#session_and_associate",
                                        as: :doctor_session
    get ":id/doctor-signin/"        => "invites#signin",
                                        as: :signin

    get ":id/doctor/:id"            => "doctors#show",
                                        as: :doctor
    get ":id/doctors"               => "doctors#index",
                                        as: :doctors
    post ":id/doctors"              => "doctors#invite_doctor",
                                        as: :invite_doctor

    get ":id/carers"                => "carers#index",
                                        as: :carers
    get ":id/carers/:id"            => "carers#show",
                                        as: :carer
    post ":id/carers"               => "carers#invite_carer",
                                        as: :invite_carer
    get ":id/carer-signup/:email"   => "carers#new",
                                        as: :new_carer
  end

  resources :doctors do
  end
  namespace :doctors do
    get ":id/patient-signin/:email" => "invites#existing",
                                        as: :existing_patient
    post ":id/session"              => "invites#session_and_associate",
                                        as: :patient_session

    post ":id/patient-signup/"      => "invites#create",
                                        as: :create_patient
    get ":id/patient-signup/:email" => "invites#new",
                                        as: :new_patient
    post ":id/patients"             => "patients#invite_patient",
                                        as: :invite_patient
    get ":id/patient/:id"           => "patients#show",
                                        as: :patient
    get ":id/patients"              => "patients#index",
                                        as: :patients
  end

  resources :carers, only: [:show]
  namespace :carers do
    resources :patients, only: [:show]

  end

  resources :sessions
  get "logout"                      => "sessions#destroy_doctor",
                                        as: :logout_doctor
  get "logout"                      => "sessions#destroy_patient",
                                        as: :logout_patient
  get "logout"                      => "sessions#destroy_carer",
                                        as: :logout_carer

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@patient = Patient.new
		@doctor = Doctor.new
		# @session = Session.new
	end
end

app/views/home/index.html.erb
<div id="banner">
  <div class="hero-unit text-center">
    <div id="banner-copy">
      <div id="title">
        <h1>Tredule</h1>
      </div>
      <div id="tagline">
        <h3>Manage your treatment with the help of those who care</h3>
      </div>
      <div id="product-description">
        Tredule will help you and those who care about you make sure that you never miss a beat when it comes to your treatment
      </div>
    </div><!-- end of #banner-copy -->
    <div id="central-signup">
      <div class='row-fluid'>
        <div id='patient-signup'>
          <h2>Patients</h2>
          <%= simple_form_for(@patient,:url => patients_path, :method => :post, :html => {:class => 'form-horizontal' }) do |f| %>
            <%= f.input :username %>
            <%= f.input :email %>
            <%= f.input :phone %>
            <%= f.input :password %>
          <%= f.button :submit, 'Sign-Up!' %>
          <% end %>
        </div><!-- end of #patient-signup -->
        <div id='doctor-signup'>
          <h2>Doctors</h2>
          <%= simple_form_for(@doctor, :url => doctors_path, :method => :post, :html => {:class => 'form-horizontal' }) do |f| %>
            <%= f.input :username %>
            <%= f.input :email %>
            <%= f.input :phone %>
            <%= f.input :speciality, :as => :grouped_select, :collection => [['Family', ['General Practioner']],['Adult', ['Surgeon']], ['Childrens', ['Pediatrics']], ['Sport', ['Physiotherapy', 'Orthopedics']]], :group_method => :last %>
            <%= f.input :password %>
          <%= f.button :submit, 'Create Account' %>
          <% end %>
        </div><!-- end of #doctor-signup -->
        <div id="user-sign-in">
          <!-- ***************** -->
          <h2>Sign-in</h2>
          <%= simple_form_for :sessions, url: sessions_path, method: 'POST' do |f| %>
              <%= f.input :email %>
              <%= f.input :password %>
            <%= f.button :submit, 'Sign-in', class:"btn btn-custom-lighten" %>
          <% end %>
          <!-- *************** -->
        </div>
      </div><!-- #row-fluid -->
    </div><!-- end of #central-signup -->
  </div>
</div>