config/routes.rb
Railsplate::Application.routes.draw do
  root to: 'home#index'

  resources :patients
  namespace :patients do
    get ":id/doctor-signup/:email"  => "invites#new",
                                        as: :new_doctor
    post ":id/doctor-signup/"       => "invites#create",
                                        as: :create_doctor
    post ":id/carer-signup/"        => "invites#create_carer",
                                        as: :create_carer
    get ":id/doctor-signin/:email"  => "invites#existing",
                                        as: :existing_doctor
    post ":id/session"              => "invites#session_and_associate",
                                        as: :doctor_session
    get ":id/doctor-signin/"        => "invites#signin",
                                        as: :signin

    get ":id/doctor/:id"            => "doctors#show",
                                        as: :doctor
    get ":id/doctors"               => "doctors#index",
                                        as: :doctors
    post ":id/doctors"              => "doctors#invite_doctor",
                                        as: :invite_doctor

    get ":id/carers"                => "carers#index",
                                        as: :carers
    get ":id/carers/:id"            => "carers#show",
                                        as: :carer
    post ":id/carers"               => "carers#invite_carer",
                                        as: :invite_carer
    get ":id/carer-signup/:email"   => "carers#new",
                                        as: :new_carer
  end

  resources :doctors do
  end
  namespace :doctors do
    get ":id/patient-signin/:email" => "invites#existing",
                                        as: :existing_patient
    post ":id/session"              => "invites#session_and_associate",
                                        as: :patient_session

    post ":id/patient-signup/"      => "invites#create",
                                        as: :create_patient
    get ":id/patient-signup/:email" => "invites#new",
                                        as: :new_patient
    post ":id/patients"             => "patients#invite_patient",
                                        as: :invite_patient
    get ":id/patient/:id"           => "patients#show",
                                        as: :patient
    get ":id/patients"              => "patients#index",
                                        as: :patients
  end

  resources :carers, only: [:show]
  namespace :carers do
    resources :patients, only: [:show]

  end

  resources :sessions
  get "logout"                      => "sessions#destroy_doctor",
                                        as: :logout_doctor
  get "logout"                      => "sessions#destroy_patient",
                                        as: :logout_patient
  get "logout"                      => "sessions#destroy_carer",
                                        as: :logout_carer

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <title><%= content_for?(:title) ? yield(:title) : "Tredule" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Tredule</a>
          <div class="user_nav pull-right">
            <% if current_doctor %>
              <p>Logged in as: <%= current_doctor.username.capitalize %></br>
              <%= link_to "Logout", logout_doctor_path %> |
              <%= link_to "My Profile", doctor_path(current_doctor) %>
            <% end %>
            <% if current_patient %>
              <p>Logged in as: <%= current_patient.username.capitalize %></br>
              <%= link_to "Logout", logout_patient_path %> |
              <%= link_to "My Profile", patient_path(current_patient) %>
            <% end %>
            <% if current_carer %>
              <p>Logged in as: <%= current_carer.username.capitalize %></br>
              <%= link_to "Logout", logout_carer_path %> |
              <%= link_to "My Profile", carer_path(current_carer) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <%=session.inspect%>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>